"""
Auto-generated version info. BUILD_NUMBER is incremented by pre-commit hook.
CHANGELOG is populated from recent git log entries.
"""

VERSION = "0.1.2"
BUILD_NUMBER = 499
# NOTE: Keep this list short (~8 entries). Remove old ones as new ones land.
CHANGELOG = [
    "b499: THE REAL FURNITURE ARRIVED. Every stand-in room prop is replaced with purpose-made art from four new sheets: actual treasure chests (closed, open, banded), an anvil and glowing forges for the blacksmith, striped market stalls for the vendor, skull-crested locked doors, hooded shrine statues, a crystal ball for the Oracle, glowing portal circles for warps, a taxidermy bench with mounted bull skull, a full bookshelf for libraries, alchemy benches and stills, weapon racks and armor stands for the war room, a skull altar, and proper stone staircases -- lit steps going up, dark steps descending. Gardens bloom with lotus, roses and leafy plants, and a new flora debris group sprinkles flowers, ferns and berries through the caves.",
    "b498: LIVELIER ROOMS, SNEAKIER MONSTERS. (1) Room props and floor debris shrank and scattered -- every prop lands at a seeded off-center spot instead of museum-centered, so no two chest rooms pose alike. (2) Monster rooms lost their totem: the big red M IS the monster (entities get glyphs, rooms get props). (3) Monsters now prowl into themed rooms: a wanderer can lurk in a chest room, a garden or on the stairs like a mimic -- fight it and the room comes back intact underneath. Entrances, warps, vendor camps, locked dungeons and Zotle chambers stay monster-free ground.",
    "b497: ROOMS SHOW THEIR CONTENTS. The big centered room letters are gone -- each themed room now draws its identity as ART in the room itself: gold and coin pouches in chest rooms, a horned candelabra on altars, tomes in libraries, coffins in tombs, iron grates on locked dungeons, a bubbling cauldron for the alchemist, a war banner, rune stones for the Oracle and Zotle, a skull totem marking monster lairs, a wooden sign at the vendor, blue springs at pools -- 35 hand-painted props from two new sheets. Ladders up and pits down are drawn right on the floor. The letter survives as a tiny color-coded badge in the room's corner, so nothing is lost for veterans.",
    "b496: GHOST OUTLINE EXORCISM. The b495 debris props carried a faint pale rim -- leftover checkerboard from the source sheets' baked-in background. Every prop is now defringed at full resolution: light unsaturated rim pixels eroded, remaining blend unmixed into semi-transparent dark anti-aliasing, and cobwebs matted into a proper translucent film (alpha from darkness, so strands drape over the floor instead of sitting on a gray ghost). Props read as painted onto the dirt at every zoom.",
    "b495: HAND-PAINTED DEBRIS. The b494 vector doodles are replaced with 67 real pixel-art props sliced from two painted debris sheets: bone piles, skulls, slumped skeletons, broken pottery, rubble and bricks, cobwebs, mushrooms, moss, crystals, chains, smashed crates, dust piles, stalagmites and glistening goo. Same seeded placement (about 4 in 10 plain floors, off-center so glyphs stay readable, webs cling to corners, themed rooms keep their own scenery). Curated so nothing on the floor reads as loot -- no bottles, gold, scrolls or weapons to bait a wasted tap.",
    "b494: CAVE DEBRIS. The drawn floors now tell little stories: skulls and scattered bones, floor cracks, moss patches, pebble piles, corner cobwebs, wild mushrooms, and the odd glistening puddle -- all drawn procedurally, seeded per room (about a third of plain floors get one), placed off-center so the room glyphs stay readable. Themed rooms keep their own scenery. Zero image payload, crisp at every zoom.",
    "b493: THE CAVERN IS NOW DRAWN, NOT STAMPED. The pre-painted tile sheet is retired for a procedural renderer: the map background is drawn on a canvas at your screen's native resolution -- rock-blob walls, speckled dirt floors, entrance gaps exactly where the passages are, themed color glows (gold hoards, blue pools, violet altars, green gardens). Every cell is seeded by its position, so no two rooms repeat, ever, and walls flow as one continuous cavern instead of 64 stamps. Crisper at every zoom level, infinitely varied, and the app shell drops ~430KB of embedded tile images. Solid rock is now textured too -- no more flat grey wall slabs.",
    "b492: TILES YOU CAN ACTUALLY SEE. Playtest feedback: too dark, too repetitive. (1) A gamma/contrast/saturation lift is baked into every tile so the stone texture and warm floors read at 42px on a dark phone screen -- entrances stay clearly dark. (2) Repetition fought on three fronts: each entrance mask now draws from EVERY family tile and rotation whose openings fit (including the mossy decorated rooms), gets 4 variants instead of 2-3, and each variant carries a subtle lighting shift -- adjacent rooms finally look like different rooms.",
]
